# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:light
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.15.2
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# +
# Goal: Check if a given python file is generated by jupytext or not.
# This is for experimentation only.
# For the final code, see src/utils/jupytext_utils.py
# -

import os
os.getcwd()

file_path = 'get ticker info.py'
# file_path = '../utils/date_utils.py'
with open(file_path) as fp:
    text = fp.read()
lines = text.splitlines()
print(lines)

# Mimicing the approach used in
# https://github.com/mwouts/jupytext/blob/main/src/jupytext/formats.py -> divine_format()
from jupytext.header import header_to_metadata_and_cell
comment = "#"
metadata, _, _, _ = header_to_metadata_and_cell(lines, comment, "")
print(metadata)

metadata.keys()

# +
# Mimicing the approach used in
# https://github.com/mwouts/jupytext/blob/main/src/jupytext/formats.py -> divine_format()
from jupytext.header import header_to_metadata_and_cell
def generated_by_jupytext(file_path):
    with open(file_path) as fp:
        text = fp.read()
    lines = text.splitlines()
    comment = "#"
    metadata, _, _, _ = header_to_metadata_and_cell(lines, comment, "")
    result = 'jupytext' in metadata.keys()
    return result

print(generated_by_jupytext('get ticker info.py'))
print(generated_by_jupytext('../utils/date_utils.py'))
